CREATE TABLE ACCOUNTS (
    ACCOUNT_ID NUMBER PRIMARY KEY,
    TYPE VARCHAR(10) CHECK(TYPE IN ('CUSTOMER', 'EMPLOYEE')),
    USERNAME VARCHAR(20) CHECK (REGEXP_LIKE(USERNAME, '^[^0-9]+$')),
    ACCOUNT_PASSWORD VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    CONSTRAINT email_unique UNIQUE (EMAIL)
);

CREATE TABLE INVENTORY (
    ITEM_ID NUMBER PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    MANUFACTURER VARCHAR(20) NOT NULL,
    STOCK NUMBER NOT NULL,
    PRICE_PER_UNIT NUMBER NOT NULL
);

CREATE TABLE LOCATIONS (
    LOCATION_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER REFERENCES ACCOUNTS(ACCOUNT_ID),
    COUNTY VARCHAR(20),
    CITY VARCHAR(20) NOT NULL,
    STREET VARCHAR(20),
    STREET_NUMBER NUMBER
);

CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    ORDERED_ITEM_ID NUMBER REFERENCES INVENTORY(ITEM_ID),
    ORDER_AMOUNT NUMBER NOT NULL,
    ORDER_DESTINATION_ID NUMBER REFERENCES LOCATIONS(LOCATION_ID),
    ORDER_DATE DATE NOT NULL,
    CUSTOMER_ID NUMBER REFERENCES ACCOUNTS(ACCOUNT_ID)
);