
-- Insert data into ACCOUNTS table
INSERT INTO ACCOUNTS (ACCOUNT_ID, TYPE, USERNAME, ACCOUNT_PASSWORD, EMAIL)
VALUES
(1, 'CUSTOMER', 'IonPopescu', 'securepass1', 'ion.popescu@email.com');

INSERT INTO ACCOUNTS (ACCOUNT_ID, TYPE, USERNAME, ACCOUNT_PASSWORD, EMAIL)
VALUES
(2, 'EMPLOYEE', 'admin', 'employeepass', 'employee@email.com');

INSERT INTO ACCOUNTS (ACCOUNT_ID, TYPE, USERNAME, ACCOUNT_PASSWORD, EMAIL)
VALUES
(3, 'CUSTOMER', 'MihaiGeorgescu', 'mypassword3', 'mihai.georgescu@email.com');

INSERT INTO ACCOUNTS (ACCOUNT_ID, TYPE, USERNAME, ACCOUNT_PASSWORD, EMAIL)
VALUES
(4, 'CUSTOMER', 'ElenaVasile', 'secret123', 'elena.vasile@email.com');

INSERT INTO ACCOUNTS (ACCOUNT_ID, TYPE, USERNAME, ACCOUNT_PASSWORD, EMAIL)
VALUES
(5, 'CUSTOMER', 'RaduConstantin', 'radu567', 'radu.constantin@email.com');

-- Insert data into INVENTORY table
INSERT INTO INVENTORY (ITEM_ID, NAME, MANUFACTURER, STOCK, PRICE_PER_UNIT)
VALUES
(1, 'Laptop', 'Dell', 10, 1200);

INSERT INTO INVENTORY (ITEM_ID, NAME, MANUFACTURER, STOCK, PRICE_PER_UNIT)
VALUES
(2, 'Smartphone', 'Samsung', 20, 800);

INSERT INTO INVENTORY (ITEM_ID, NAME, MANUFACTURER, STOCK, PRICE_PER_UNIT)
VALUES
(3, 'Printer', 'HP', 5, 300);

INSERT INTO INVENTORY (ITEM_ID, NAME, MANUFACTURER, STOCK, PRICE_PER_UNIT)
VALUES
(4, 'Headphones', 'Sony', 15, 100);

INSERT INTO INVENTORY (ITEM_ID, NAME, MANUFACTURER, STOCK, PRICE_PER_UNIT)
VALUES
(5, 'Tablet', 'Apple', 8, 1500);

-- Insert data into LOCATIONS table
INSERT INTO LOCATIONS (LOCATION_ID, CUSTOMER_ID, COUNTY, CITY, STREET, STREET_NUMBER)
VALUES
(1, 1, 'Bucharest', 'Sector 1', 'Victoriei', 15);

INSERT INTO LOCATIONS (LOCATION_ID, CUSTOMER_ID, COUNTY, CITY, STREET, STREET_NUMBER)
VALUES
(3, 3, 'Timis', 'Timisoara', 'Piata Unirii', 10);

INSERT INTO LOCATIONS (LOCATION_ID, CUSTOMER_ID, COUNTY, CITY, STREET, STREET_NUMBER)
VALUES
(4, 4, 'Constanta', 'Constanta', 'Mamaia', 5);

INSERT INTO LOCATIONS (LOCATION_ID, CUSTOMER_ID, COUNTY, CITY, STREET, STREET_NUMBER)
VALUES
(5, 5, 'Iasi', 'Iasi', 'Stefan cel Mare', 30);

-- Insert data into ORDERS table
INSERT INTO ORDERS (ORDER_ID, ORDERED_ITEM_ID, ORDER_AMOUNT, ORDER_DESTINATION_ID, ORDER_DATE, CUSTOMER_ID)
VALUES
(1, 1, 3, 1, TO_DATE('2024-01-05', 'YYYY-MM-DD'), 1);

INSERT INTO ORDERS (ORDER_ID, ORDERED_ITEM_ID, ORDER_AMOUNT, ORDER_DESTINATION_ID, ORDER_DATE, CUSTOMER_ID)
VALUES
(2, 2, 2, 1, TO_DATE('2024-01-06', 'YYYY-MM-DD'), 1);

INSERT INTO ORDERS (ORDER_ID, ORDERED_ITEM_ID, ORDER_AMOUNT, ORDER_DESTINATION_ID, ORDER_DATE, CUSTOMER_ID)
VALUES
(3, 3, 5, 3, TO_DATE('2024-01-07', 'YYYY-MM-DD'), 3);

INSERT INTO ORDERS (ORDER_ID, ORDERED_ITEM_ID, ORDER_AMOUNT, ORDER_DESTINATION_ID, ORDER_DATE, CUSTOMER_ID)
VALUES
(4, 4, 1, 4, TO_DATE('2024-01-08', 'YYYY-MM-DD'), 4);

INSERT INTO ORDERS (ORDER_ID, ORDERED_ITEM_ID, ORDER_AMOUNT, ORDER_DESTINATION_ID, ORDER_DATE, CUSTOMER_ID)
VALUES
(5, 5, 4, 5, TO_DATE('2024-01-09', 'YYYY-MM-DD'), 5);
